<?php
/**
 * Created by PhpStorm.
 * User: liaopeng
 * Date: 2018/12/10
 * Time: 3:09 PM
 */
namespace lpsoft\lpii\controllers;
use \yii\web\Controller;
use Yii;
class BuildController extends Controller
{
    //当前域名
    public $domain;
    //当前路径
    public $top_path;

    //初始货获取路径信息
    public function init()
    {
        $this->domain= Yii::$app->request->getHostInfo();

        $path =  dirname(__FILE__);
        $top_path=explode("vendor",$path);
        $this->top_path=$top_path[0];

        parent::init(); // TODO: Change the autogenerated stub
    }
    //统一接收
    public function P($key)
    {
        $data = isset($_POST[$key])?$_POST[$key]:null;
        return $data;
    }
    //统一回复
    public function R($status=100,$msg="",$data=null){
        \Yii::$app->response->headers->set('Access-Control-Allow-Origin', '*');
        \Yii::$app->response->format = yii\web\Response::FORMAT_JSON;
        \Yii::$app->response->data = [
            'status' => $status,
            'msg' => $msg,
            'data' => $data
        ];
        \Yii::$app->response->send();
        exit();

    }


}