<?php
/**
 * Created by PhpStorm.
 * User: liaopeng
 * Date: 2018/12/10
 * Time: 4:31 PM
 */
namespace lpsoft\lpii\models;
use \yii\base\Model;
class Build extends Model
{
    //当前域名
    public $domain;
    //当前路径
    public $top_path;
    //初使货路径哉名
    public function init()
    {
        $this->domain= Yii::$app->request->getHostInfo();

        $path =  dirname(__FILE__);
        $top_path=explode("vendor",$path);
        $this->top_path=$top_path[0];
        parent::init(); // TODO: Change the autogenerated stub
    }
    //获取项目路径
    public static function getYiiAppPath($appname)
    {
        return \Yii::getAlias("@".$appname);

    }

}